// Hand-crafted mock recipes used in M1 before the Anthropic call is wired up.
// Same shape as the real Recipe type from spec §9, so swapping to live data
// in M2 is a one-line change in Results.tsx.

import type { Recipe } from "./types";

export const MOCK_RECIPES: Recipe[] = [
  {
    id: "mock-tomato-rasam",
    source: {
      url: "https://www.archanaskitchen.com/tomato-rasam-recipe",
      siteName: "archanaskitchen.com",
      imageUrl: null,
      fetchedAt: "2026-05-16T18:00:00Z",
    },
    title: "Tomato rasam with steamed rice",
    tagline: "Tangy, peppery, and ready in under 30 minutes",
    servings: { base: 2, current: 2 },
    times: { prepMinutes: 10, cookMinutes: 20, totalMinutes: 30 },
    difficulty: { score: 2, label: "weeknight easy" },
    calories: { perServing: 280, inferenceSource: "page" },
    equipment: ["pressure cooker"],
    makeAhead: "Soak the toor dal for at least 30 minutes before starting.",
    dietFlags: ["vegan", "gluten-free"],
    pairsWith: ["papad", "coconut chutney", "steamed rice"],
    whyPicked: ["30m", "comforting", "south indian"],
    ingredients: [
      {
        name: "ripe tomatoes",
        quantity: 3,
        unit: null,
        group: null,
        instamart: {
          available: true,
          productId: "p1",
          price: 40,
          classification: "pantry-staple",
        },
      },
      {
        name: "toor dal",
        quantity: 0.25,
        unit: "cup",
        group: null,
        instamart: {
          available: true,
          productId: "p2",
          price: 30,
          classification: "pantry-staple",
        },
      },
      {
        name: "tamarind paste",
        quantity: 1,
        unit: "tsp",
        group: null,
        instamart: {
          available: false,
          productId: null,
          price: null,
          classification: "specialty",
        },
      },
      {
        name: "black pepper",
        quantity: 1,
        unit: "tsp",
        group: "For the rasam powder",
        instamart: {
          available: true,
          productId: "p3",
          price: 60,
          classification: "pantry-staple",
        },
      },
      {
        name: "cumin seeds",
        quantity: 1,
        unit: "tsp",
        group: "For the rasam powder",
        instamart: {
          available: true,
          productId: "p4",
          price: 50,
          classification: "pantry-staple",
        },
      },
      {
        name: "curry leaves",
        quantity: 8,
        unit: null,
        group: "For the tempering",
        instamart: {
          available: false,
          productId: null,
          price: null,
          classification: "specialty",
        },
      },
      {
        name: "mustard seeds",
        quantity: 0.5,
        unit: "tsp",
        group: "For the tempering",
        instamart: {
          available: true,
          productId: "p5",
          price: 40,
          classification: "pantry-staple",
        },
      },
      {
        name: "asafoetida (hing)",
        quantity: 0.25,
        unit: "tsp",
        group: "For the tempering",
        instamart: {
          available: true,
          productId: "p6",
          price: 90,
          classification: "likely-available",
        },
      },
      {
        name: "ghee",
        quantity: 1,
        unit: "tbsp",
        group: "For the tempering",
        instamart: {
          available: true,
          productId: "p7",
          price: 120,
          classification: "pantry-staple",
        },
      },
      {
        name: "fresh coriander",
        quantity: 2,
        unit: "tbsp",
        group: null,
        instamart: {
          available: true,
          productId: "p8",
          price: 20,
          classification: "pantry-staple",
        },
      },
    ],
    steps: [
      {
        number: 1,
        text: "Pressure cook the toor dal with 1 cup water and a pinch of turmeric for 3 whistles. Mash gently and set aside.",
        timerSeconds: null,
      },
      {
        number: 2,
        text: "Roughly chop the tomatoes. In a large pot, add the tomatoes, tamarind paste, 2 cups of water, and a pinch of salt.",
        timerSeconds: null,
      },
      {
        number: 3,
        text: "Bring to a simmer over medium heat. Cook for 8 minutes until the tomatoes break down.",
        timerSeconds: 480,
      },
      {
        number: 4,
        text: "Meanwhile, dry-roast the pepper and cumin in a small pan until fragrant, about 1 minute. Grind to a coarse powder.",
        timerSeconds: 60,
      },
      {
        number: 5,
        text: "Stir the rasam powder and cooked dal into the tomato mixture. Simmer for 5 minutes.",
        timerSeconds: 300,
      },
      {
        number: 6,
        text: "In a small pan, heat the ghee. Add mustard seeds; once they pop, add curry leaves and asafoetida.",
        timerSeconds: null,
      },
      {
        number: 7,
        text: "Pour the tempering over the rasam. Stir once.",
        timerSeconds: null,
      },
      {
        number: 8,
        text: "Garnish with chopped coriander. Taste and adjust salt.",
        timerSeconds: null,
      },
      {
        number: 9,
        text: "Serve hot over steamed rice with papad and coconut chutney on the side.",
        timerSeconds: null,
      },
    ],
  },
  {
    id: "mock-cherry-tomato-pasta",
    source: {
      url: "https://www.bbcgoodfood.com/recipes/cherry-tomato-pasta",
      siteName: "bbcgoodfood.com",
      imageUrl: null,
      fetchedAt: "2026-05-16T18:00:00Z",
    },
    title: "Cherry tomato pasta with garlic and basil",
    tagline: "Bright, garlicky, and on the table in 20 minutes",
    servings: { base: 2, current: 2 },
    times: { prepMinutes: 5, cookMinutes: 15, totalMinutes: 20 },
    difficulty: { score: 1, label: "effortless" },
    calories: { perServing: 420, inferenceSource: "page" },
    equipment: [],
    makeAhead: null,
    dietFlags: ["vegetarian", "contains gluten", "contains dairy"],
    pairsWith: null,
    whyPicked: ["under 30m", "comforting", "all on instamart"],
    ingredients: [
      {
        name: "spaghetti",
        quantity: 200,
        unit: "g",
        group: null,
        instamart: {
          available: true,
          productId: "p9",
          price: 95,
          classification: "pantry-staple",
        },
      },
      {
        name: "cherry tomatoes",
        quantity: 300,
        unit: "g",
        group: null,
        instamart: {
          available: true,
          productId: "p10",
          price: 80,
          classification: "pantry-staple",
        },
      },
      {
        name: "garlic cloves",
        quantity: 4,
        unit: null,
        group: null,
        instamart: {
          available: true,
          productId: "p11",
          price: 35,
          classification: "pantry-staple",
        },
      },
      {
        name: "olive oil",
        quantity: 3,
        unit: "tbsp",
        group: null,
        instamart: {
          available: true,
          productId: "p12",
          price: 320,
          classification: "pantry-staple",
        },
      },
      {
        name: "fresh basil leaves",
        quantity: 1,
        unit: "cup",
        group: null,
        instamart: {
          available: true,
          productId: "p13",
          price: 50,
          classification: "likely-available",
        },
      },
      {
        name: "parmesan, grated",
        quantity: 30,
        unit: "g",
        group: null,
        instamart: {
          available: true,
          productId: "p14",
          price: 280,
          classification: "likely-available",
        },
      },
      {
        name: "red chili flakes",
        quantity: 0.5,
        unit: "tsp",
        group: null,
        instamart: {
          available: true,
          productId: "p15",
          price: 60,
          classification: "pantry-staple",
        },
      },
    ],
    steps: [
      {
        number: 1,
        text: "Bring a large pot of salted water to a rolling boil.",
        timerSeconds: null,
      },
      {
        number: 2,
        text: "Add the spaghetti and cook for 9–10 minutes, stirring occasionally, until al dente.",
        timerSeconds: 540,
      },
      {
        number: 3,
        text: "Meanwhile, halve the cherry tomatoes and finely slice the garlic.",
        timerSeconds: null,
      },
      {
        number: 4,
        text: "In a wide pan, warm the olive oil over medium heat. Add garlic and chili flakes. Cook for 1 minute until fragrant, not browned.",
        timerSeconds: 60,
      },
      {
        number: 5,
        text: "Add the cherry tomatoes and a pinch of salt. Cook for 5 minutes, stirring occasionally, until the tomatoes burst and release their juice.",
        timerSeconds: 300,
      },
      {
        number: 6,
        text: "Reserve ½ cup of pasta water, then drain the spaghetti.",
        timerSeconds: null,
      },
      {
        number: 7,
        text: "Tip the drained spaghetti into the tomato pan with a splash of pasta water. Toss for 1 minute until the sauce clings.",
        timerSeconds: 60,
      },
      {
        number: 8,
        text: "Tear in the basil leaves, top with grated parmesan, and serve immediately.",
        timerSeconds: null,
      },
    ],
  },
  {
    id: "mock-chana-masala",
    source: {
      url: "https://www.indianhealthyrecipes.com/chana-masala",
      siteName: "indianhealthyrecipes.com",
      imageUrl: null,
      fetchedAt: "2026-05-16T18:00:00Z",
    },
    title: "Chana masala with onions and tomato",
    tagline: "Hearty, deeply spiced chickpea curry — comfort food classic",
    servings: { base: 3, current: 3 },
    times: { prepMinutes: 15, cookMinutes: 30, totalMinutes: 45 },
    difficulty: { score: 3, label: "needs a bit of focus" },
    calories: { perServing: 340, inferenceSource: "estimated" },
    equipment: [],
    makeAhead:
      "Soak 1 cup of dried chickpeas overnight, or use 2 cans of cooked chickpeas for a faster start.",
    dietFlags: ["vegan", "gluten-free"],
    pairsWith: ["basmati rice", "naan", "raita"],
    whyPicked: ["north indian", "comforting", "weekend"],
    ingredients: [
      {
        name: "chickpeas, cooked",
        quantity: 2,
        unit: "cup",
        group: null,
        instamart: {
          available: true,
          productId: "p16",
          price: 60,
          classification: "pantry-staple",
        },
      },
      {
        name: "onion, finely chopped",
        quantity: 2,
        unit: null,
        group: null,
        instamart: {
          available: true,
          productId: "p17",
          price: 30,
          classification: "pantry-staple",
        },
      },
      {
        name: "tomatoes, pureed",
        quantity: 3,
        unit: null,
        group: null,
        instamart: {
          available: true,
          productId: "p18",
          price: 50,
          classification: "pantry-staple",
        },
      },
      {
        name: "ginger-garlic paste",
        quantity: 2,
        unit: "tsp",
        group: null,
        instamart: {
          available: true,
          productId: "p19",
          price: 45,
          classification: "pantry-staple",
        },
      },
      {
        name: "green chilies, slit",
        quantity: 2,
        unit: null,
        group: null,
        instamart: {
          available: true,
          productId: "p20",
          price: 15,
          classification: "pantry-staple",
        },
      },
      {
        name: "garam masala",
        quantity: 1,
        unit: "tsp",
        group: "Spices",
        instamart: {
          available: true,
          productId: "p21",
          price: 80,
          classification: "pantry-staple",
        },
      },
      {
        name: "cumin powder",
        quantity: 1,
        unit: "tsp",
        group: "Spices",
        instamart: {
          available: true,
          productId: "p22",
          price: 50,
          classification: "pantry-staple",
        },
      },
      {
        name: "coriander powder",
        quantity: 1,
        unit: "tbsp",
        group: "Spices",
        instamart: {
          available: true,
          productId: "p23",
          price: 50,
          classification: "pantry-staple",
        },
      },
      {
        name: "amchur (dried mango powder)",
        quantity: 0.5,
        unit: "tsp",
        group: "Spices",
        instamart: {
          available: false,
          productId: null,
          price: null,
          classification: "specialty",
        },
      },
      {
        name: "oil",
        quantity: 2,
        unit: "tbsp",
        group: null,
        instamart: {
          available: true,
          productId: "p24",
          price: 180,
          classification: "pantry-staple",
        },
      },
      {
        name: "fresh coriander, for garnish",
        quantity: 2,
        unit: "tbsp",
        group: null,
        instamart: {
          available: true,
          productId: "p25",
          price: 20,
          classification: "pantry-staple",
        },
      },
    ],
    steps: [
      {
        number: 1,
        text: "Heat the oil in a heavy-bottomed pan over medium-high heat. Add onions and a pinch of salt.",
        timerSeconds: null,
      },
      {
        number: 2,
        text: "Sauté the onions for 8 minutes, stirring frequently, until deep golden brown. Don't rush this — the color is the flavor.",
        timerSeconds: 480,
      },
      {
        number: 3,
        text: "Add the ginger-garlic paste and green chilies. Stir for 1 minute until raw smell disappears.",
        timerSeconds: 60,
      },
      {
        number: 4,
        text: "Add the pureed tomatoes and all the spice powders (except garam masala). Cook for 5 minutes until oil starts to separate.",
        timerSeconds: 300,
      },
      {
        number: 5,
        text: "Tip in the chickpeas with 1 cup of water. Bring to a simmer.",
        timerSeconds: null,
      },
      {
        number: 6,
        text: "Cover partially and simmer for 12 minutes, stirring occasionally. Mash a few chickpeas against the side of the pan to thicken the gravy.",
        timerSeconds: 720,
      },
      {
        number: 7,
        text: "Sprinkle in the garam masala and amchur. Stir, taste, and adjust salt.",
        timerSeconds: null,
      },
      {
        number: 8,
        text: "Garnish with fresh coriander and serve hot with basmati rice or naan.",
        timerSeconds: null,
      },
    ],
  },
];

export function findMockRecipe(id: string): Recipe | undefined {
  return MOCK_RECIPES.find((r) => r.id === id);
}
